spring:
  cloud:
    inetutils:
      preferred-networks:
        - 172.21.
  application:
    name: trace-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/trace_db}
    username: ${SPRING_DATASOURCE_USERNAME:agritrace}
    password: ${SPRING_DATASOURCE_PASSWORD:agritrace2026}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT:8083}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9093}
  client:
    user-service:
      address: ${GRPC_USER_SERVICE:static://user-service:9090}
      negotiationType: plaintext
    product-service:
      address: ${GRPC_PRODUCT_SERVICE:static://product-service:9090}
      negotiationType: plaintext

resilience4j:
  circuitbreaker:
    instances:
      userServiceGrpc:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
      productServiceGrpc:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9083}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}

logging:
  level:
    root: WARN
    com.agritrace: WARN

trace:
  geofence:
    default-radius-km: ${TRACE_GEOFENCE_DEFAULT_RADIUS_KM:5.0}
    packaging-radius-km: ${TRACE_GEOFENCE_PACKAGING_RADIUS_KM:20.0}
    inspection-radius-km: ${TRACE_GEOFENCE_INSPECTION_RADIUS_KM:20.0}
