/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#10b981",
        "inverse-primary": "#4edea3",
        "on-error": "#ffffff",
        "on-secondary-container": "#3c6c54",
        "primary-fixed-dim": "#4edea3",
        "secondary-fixed": "#baeed1",
        "on-tertiary-fixed": "#410005",
        "surface-bright": "#f9f9ff",
        "tertiary": "#a43a3a",
        "on-primary-container": "#00422b",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdad7",
        "surface-variant": "#d8e3fb",
        "on-surface": "#111c2d",
        "primary-fixed": "#6ffbbe",
        "surface-dim": "#cfdaf2",
        "surface-tint": "#006c49",
        "surface-container-high": "#dee8ff",
        "background": "#f9f9ff",
        "primary": "#006c49",
        "outline": "#6c7a71",
        "surface-container-low": "#f0f3ff",
        "tertiary-container": "#fc7c78",
        "inverse-on-surface": "#ecf1ff",
        "secondary": "#376850",
        "on-tertiary-fixed-variant": "#842225",
        "on-surface-variant": "#3c4a42",
        "on-tertiary-container": "#711419",
        "on-secondary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002113",
        "tertiary-fixed-dim": "#ffb3af",
        "secondary-container": "#b7ebce",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#111c2d",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#005236",
        "error-container": "#ffdad6",
        "surface": "#f9f9ff",
        "surface-container": "#e7eeff",
        "surface-container-highest": "#d8e3fb",
        "inverse-surface": "#263143",
        "outline-variant": "#bbcabf",
        "on-secondary-fixed-variant": "#1e4f3a",
        "secondary-fixed-dim": "#9ed2b5",
      },
      fontFamily: {
        sans: ["Inter", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}

