package com.agritrace.product.dto;

import java.util.UUID;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CreateBatchRequest - Phase 3.1 (Updated)
 * 
 * DTO for creating a new batch
 * 
 * Changes from V1:
 * - Removed batchCode (auto-generated by service)
 * - Replaced cropId with productId
 * - Renamed facilityId to farmId (semantic clarity)
 * - Added quantity field with validation
 * - Removed status (always starts as CREATED)
 * - Removed currentHash (future blockchain feature)
 * 
 * Validation:
 * - farmId: Required
 * - productId: Required
 * - quantity: Required, minimum 1
 * 
 * Example:
 * {
 *   "farmId": "123e4567-e89b-12d3-a456-426614174000",
 *   "productId": "987fbc97-4bed-5078-9f07-9141ba07c9f3",
 *   "quantity": 150.5
 * }
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateBatchRequest {

    @NotNull(message = "Farm ID is required")
    private UUID farmId;

    @NotNull(message = "Product ID is required")
    private UUID productId;

    @NotNull(message = "Quantity is required")
    @Min(value = 1, message = "Quantity must be at least 1")
    private Double quantity;
    
    @NotBlank(message = "Unit is required (e.g., kg, tấn)")
    private String unit;
    
    // Accept both yyyy-MM-dd and yyyy-MM-ddTHH:mm:ss, parse in service layer.
    private String harvestDate;
    private UUID ownerId; // From Gateway X-User-Id header

    private Double farmLatitude;
    private Double farmLongitude;
}